development:
  adapter: async
  url: redis://localhost:6379/1

test:
  adapter: test
  url: redis://localhost:6379/1

production:
  adapter: redis
  # need to remove `{ "redis://localhost:6379/1" }`?
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: brain_defrost_be_production
